version: 1.0
name: DTSE-PCS-application-containerization-to-the-cloud
language: java


#  构建工具
dependencies:
  base:
    jdk: best
    maven: best
    
#  构建机器
machine:
  standard:
    euler:
      - default
    
#  构建脚本
scripts:
  - sh build.sh
  
#  构建产物
artifacts:
  package:
    - huaweicloud-solution-application-containerization-to-the-cloud-en
